export const SIGN = 'SIGN'
export const LOGOUT = 'LOGOUT'

export const LIST = 'LIST'
export const CHANGE_COLUMN_FRONTEND = 'CHANGE_COLUMN_FRONTEND'
export const CHANGE_ORDER_FRONTEND = 'CHANGE_ORDER_FRONTEND'
